services:
  proxy:
    volumes:
      - ./components/dggs/service-config.json:/static/services/dggs.json:ro
      - ./components/dggs/config/proxy/conf.extra-service.d:/etc/nginx/conf.extra-service.d/dggs:ro
