x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "200k"
    max-file: "10"

version: "3.4"
services:

  proxy:
    volumes:
      - ./optional-components/secure-data-proxy/conf.extra-service.d:/etc/nginx/conf.extra-service.d/secure-data-proxy:ro

  magpie:
    volumes:
      - ./optional-components/secure-data-proxy/config/magpie/config.yml:/opt/local/src/magpie/config/providers/secure-data-proxy.yml:ro
      - ./optional-components/secure-data-proxy/config/magpie/config.yml:/opt/local/src/magpie/config/permissions/secure-data-proxy.yml:ro
